/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xt_client_jni_Java2CJNI */

#ifndef _Included_com_xt_client_jni_Java2CJNI
#define _Included_com_xt_client_jni_Java2CJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xt_client_jni_Java2CJNI
 * Method:    java2C
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xt_client_jni_Java2CJNI_java2C
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
