/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xt_client_jni_CalculationJNITest */

#ifndef _Included_com_xt_client_jni_CalculationJNITest
#define _Included_com_xt_client_jni_CalculationJNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xt_client_jni_CalculationJNITest
 * Method:    calculationSum
 * Signature: (IILjava/lang/String;D[C[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xt_client_jni_CalculationJNITest_calculationSum
  (JNIEnv *, jobject, jint, jint, jstring, jdouble, jcharArray, jbyteArray);

JNIEXPORT jobject JNICALL Java_com_xt_client_jni_CalculationJNITest_updateObjectValue
        (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
